import { fileURLToPath } from 'node:url'

import type { OxlintConfig, OxlintOverride } from 'oxlint'

const customRulesPluginSpecifier = fileURLToPath(new URL('./manifest-plugin.ts', import.meta.url))

const antiSlopPluginSpecifier = fileURLToPath(new URL('./anti-slop/index.ts', import.meta.url))

const antiSlopEffectPluginSpecifier = fileURLToPath(
	new URL('./anti-slop/effect/index.ts', import.meta.url),
)

export const baseConfig = {
	categories: {
		correctness: 'error',
		suspicious: 'error',
		perf: 'error',
	},
	jsPlugins: [
		{ name: 'patdown-contracts', specifier: customRulesPluginSpecifier },
		{ name: 'anti-slop', specifier: antiSlopPluginSpecifier },
		{ name: 'anti-slop-effect', specifier: antiSlopEffectPluginSpecifier },
	],
	plugins: ['typescript', 'vitest', 'oxc', 'import', 'promise', 'unicorn', 'node'],
	rules: {
		'anti-slop-effect/no-manual-effect-error-tag': 'error',
		'anti-slop-effect/no-manual-tag-comparison': 'error',
		'anti-slop-effect/no-manual-tagged-construction': 'error',
		'anti-slop-effect/no-service-constructor-imports': 'error',
		'anti-slop-effect/prefer-effect-match': 'error',
		'anti-slop/no-array-filter-map': 'error',
		'anti-slop/no-chained-type-assertions': 'error',
		'anti-slop/no-conditional-empty-object-spread': 'error',
		'anti-slop/no-known-value-widening': 'error',
		'anti-slop/no-module-mocking': 'error',
		'anti-slop/no-object-parameters': 'error',
		'anti-slop/no-reduce-accumulator-copy': 'error',
		'anti-slop/no-reflect-apply': 'error',
		'anti-slop/no-reflect-get': 'error',
		'anti-slop/no-runtime-typeof': ['error', { allowInTypeGuards: true }],
		'anti-slop/no-shape-in-symbol-names': 'error',
		'anti-slop/no-unknown-parameters': 'error',
		'anti-slop/no-unknown-returns': 'error',
		'anti-slop/no-unknown-type-aliases': 'error',
		'anti-slop/no-unsafe-dictionary-type': 'error',
		'anti-slop/no-widen-then-assert': 'error',
		'anti-slop/require-readable-spacing': 'error',
		'anti-slop/require-safety-comment-for-type-assertion': 'error',
		'patdown-contracts/no-phantom-never-mapped-type': 'error',
		'patdown-contracts/no-record-string-unknown': 'error',
		'patdown-contracts/no-unconstrained-input-generic': 'error',
		'oxc/no-accumulating-spread': 'error',
		'array-callback-return': 'error',
		'complexity': ['error', 8],
		'eqeqeq': 'error',
		'max-depth': ['error', 3],
		'max-lines-per-function': ['error', 120],
		'max-params': ['error', 4],
		'no-restricted-imports': [
			'error',
			{
				patterns: ['@patdown/*/src/**', '@patdown/*/dist/**'],
			},
		],
		'no-array-constructor': 'error',
		'no-case-declarations': 'error',
		'no-console': 'error',
		'no-else-return': 'error',
		'no-fallthrough': 'error',
		'no-loop-func': 'error',
		'no-new-wrappers': 'error',
		'no-promise-executor-return': 'error',
		'no-prototype-builtins': 'error',
		'no-self-compare': 'error',
		'no-throw-literal': 'error',
		'no-underscore-dangle': ['error', { allow: ['_tag'] }],
		'no-use-before-define': 'error',
		'no-warning-comments': 'error',
		'radix': 'error',
		'require-await': 'error',
		'symbol-description': 'error',
		'node/no-new-require': 'error',
		'node/no-path-concat': 'error',
		'node/no-process-env': 'error',
		'import/no-cycle': 'error',
		'import/no-default-export': 'error',
		'import/no-relative-parent-imports': 'error',
		'import/no-self-import': 'error',
		'import/no-unassigned-import': 'error',
		'promise/always-return': 'error',
		'promise/catch-or-return': 'error',
		'promise/no-multiple-resolved': 'error',
		'promise/no-promise-in-callback': 'error',
		'typescript/await-thenable': 'error',
		'typescript/ban-ts-comment': 'error',
		'typescript/ban-types': 'error',
		'typescript/explicit-function-return-type': 'error',
		'typescript/explicit-module-boundary-types': 'error',
		'typescript/no-deprecated': 'error',
		'typescript/no-confusing-void-expression': 'error',
		'typescript/no-dynamic-delete': 'error',
		'typescript/no-empty-object-type': 'error',
		'typescript/no-explicit-any': 'error',
		'typescript/no-floating-promises': 'error',
		'typescript/no-import-type-side-effects': 'error',
		'typescript/no-invalid-void-type': 'error',
		'typescript/no-mixed-enums': 'error',
		'typescript/no-misused-promises': 'error',
		'typescript/no-namespace': 'error',
		'typescript/no-non-null-assertion': 'error',
		'typescript/no-require-imports': 'error',
		'typescript/no-unnecessary-type-parameters': 'error',
		'typescript/no-unsafe-argument': 'error',
		'typescript/no-unsafe-assignment': 'error',
		'typescript/no-unsafe-call': 'error',
		'typescript/no-unsafe-function-type': 'error',
		'typescript/no-unsafe-member-access': 'error',
		'typescript/no-unsafe-return': 'error',
		'typescript/no-var-requires': 'error',
		'typescript/non-nullable-type-assertion-style': 'error',
		'typescript/only-throw-error': 'error',
		'typescript/prefer-as-const': 'error',
		'typescript/prefer-enum-initializers': 'error',
		'typescript/prefer-includes': 'error',
		'typescript/prefer-literal-enum-member': 'error',
		'typescript/prefer-nullish-coalescing': 'error',
		'typescript/prefer-promise-reject-errors': 'error',
		'typescript/prefer-ts-expect-error': 'error',
		'typescript/promise-function-async': 'error',
		'typescript/related-getter-setter-pairs': 'error',
		'typescript/require-await': 'error',
		'typescript/return-await': 'error',
		'typescript/restrict-plus-operands': 'error',
		'typescript/strict-boolean-expressions': 'error',
		'typescript/switch-exhaustiveness-check': 'error',
		'typescript/use-unknown-in-catch-callback-variable': 'error',
		'unicorn/explicit-length-check': 'error',
		'unicorn/filename-case': ['error', { case: 'kebabCase' }],
		'unicorn/no-array-for-each': 'error',
		'unicorn/no-array-fill-with-reference-type': 'error',
		'unicorn/no-array-reduce': 'error',
		'unicorn/no-await-in-promise-methods': 'error',
		'unicorn/no-useless-undefined': 'error',
		'unicorn/prefer-node-protocol': 'error',
		'vitest/expect-expect': [
			'error',
			{ assertFunctionNames: ['expect', 'expect*', 'assert', 'assert*'] },
		],
		// Effect's `it.effect` wrappers are not recognized as Vitest test blocks by this rule.
		'vitest/no-standalone-expect': 'off',
	},
	overrides: [
		{
			files: ['**/oxlint.config.ts'],
			rules: {
				'import/no-default-export': 'off',
				'import/no-relative-parent-imports': 'off',
				'patdown-contracts/artifact-entrypoint-contract': 'error',
				'patdown-contracts/package-imports-contract': 'error',
				'patdown-contracts/source-resolution-contract': 'error',
				'patdown-contracts/vitest-test-resolution-contract': 'error',
				'patdown-contracts/vitest-tsconfig-split-contract': 'error',
				'patdown-contracts/workspace-package-verification-contract': 'error',
			},
		},
		{
			files: ['**/vitest.config.ts'],
			rules: {
				'import/no-default-export': 'off',
			},
		},
	],
	ignorePatterns: [
		'.agent/**',
		'.agents/**',
		'.claude/**',
		'.codex/**',
		'.continue/**',
		'.cursor/**',
		'.gemini/**',
		'.opencode/**',
		'.pi/**',
		'.roo/**',
		'.windsurf/**',
		'**/node_modules/**',
		'**/dist/**',
		'**/coverage/**',
		'anti-slop/**',
		'packages/oxlint-config/anti-slop/**',
	],
} satisfies OxlintConfig

const subpathImportPatterns = [
	{
		group: ['./**', '../**'],
		message: 'Use the package subpath import form (`#src/...`) instead of relative imports.',
	},
	{
		group: ['*.js', '**/*.js'],
		message:
			'Do not include `.js` in TypeScript source imports; use `#src/...` without an extension.',
	},
]

/**
 * Override that enforces subpath imports (`#src/...`) over relative imports in source files. Add to
 * your package's `overrides` array.
 */
export const subpathImportOverride = {
	files: ['src/**/*.ts', 'src/**/*.tsx', 'src/**/*.mts', 'src/**/*.cts'],
	rules: {
		'no-restricted-imports': [
			'error',
			{
				patterns: [...subpathImportPatterns],
			},
		],
	},
} satisfies OxlintOverride
